In [4]:
import tensorflow as tf
import numpy as np

In [5]:
xy = np.loadtxt( 'Data/data-01-test-score.csv', delimiter = ',', dtype = np.float32 )
x_data = xy[ :, 0 : -1 ]
y_data = xy[ :, [ -1 ] ]

In [6]:
print( x_data.shape, x_data, len( x_data ) )
print( y_data.shape, y_data )

(6, 3) [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]] 6
(6, 1) [[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]]


In [7]:
W = tf.Variable( tf.random.normal( [ 3, 1 ] ), name = 'weight' )
b = tf.Variable( tf.random.normal( [ 1 ] ), name = 'bias' )

In [17]:
@tf.function
def Hypothesis( X ):
    return tf.matmul( X, W ) + b

@tf.function
def Cost( X, Y ):
    return tf.reduce_mean( tf.square( Hypothesis( X ) - Y ) )

def Minimize( X, Y ):
    loss = lambda : Cost( X, Y )
    
    optimizer = tf.keras.optimizers.SGD( learning_rate = 1e-5 )
    optimizer.minimize( loss, [ W, b ] )

In [18]:
X = x_data
Y = y_data
for step in range( 2001 ):
    cost_val, hy_val, _ = \
        Cost( X, Y ), Hypothesis( X ), Minimize( X, Y )
    
    if step % 10 == 0:
        tf.print( step, 'Cost: ', cost_val,
             '\nPrediction: \n', hy_val )

0 Cost:  3.25509953 
Prediction: 
 [[150.688766]
 [184.325272]
 [179.873581]
 [195.881332]
 [141.590866]
 [105.142288]]
10 Cost:  3.24550629 
Prediction: 
 [[150.694412]
 [184.322662]
 [179.875977]
 [195.882355]
 [141.58786]
 [105.136497]]
20 Cost:  3.23598266 
Prediction: 
 [[150.700012]
 [184.320068]
 [179.878372]
 [195.883362]
 [141.584839]
 [105.130722]]
30 Cost:  3.22651267 
Prediction: 
 [[150.705612]
 [184.317474]
 [179.880753]
 [195.884399]
 [141.581863]
 [105.124969]]
40 Cost:  3.21709323 
Prediction: 
 [[150.711197]
 [184.314911]
 [179.883133]
 [195.885406]
 [141.578888]
 [105.119232]]
50 Cost:  3.20773 
Prediction: 
 [[150.716766]
 [184.312347]
 [179.885513]
 [195.886414]
 [141.575912]
 [105.11351]]
60 Cost:  3.1984427 
Prediction: 
 [[150.722305]
 [184.309769]
 [179.887863]
 [195.887405]
 [141.572952]
 [105.107811]]
70 Cost:  3.18918729 
Prediction: 
 [[150.727844]
 [184.307236]
 [179.890244]
 [195.888428]
 [141.570023]
 [105.102127]]
80 Cost:  3.17998958 
Prediction: 
 [[1

680 Cost:  2.71881986 
Prediction: 
 [[151.032745]
 [184.167435]
 [180.021027]
 [195.940918]
 [141.411179]
 [104.785965]]
690 Cost:  2.71245289 
Prediction: 
 [[151.037231]
 [184.165375]
 [180.022964]
 [195.94165]
 [141.40889]
 [104.78125]]
700 Cost:  2.70611954 
Prediction: 
 [[151.041718]
 [184.16333]
 [180.024887]
 [195.942368]
 [141.406601]
 [104.77655]]
710 Cost:  2.69979882 
Prediction: 
 [[151.046204]
 [184.161285]
 [180.026825]
 [195.943085]
 [141.404343]
 [104.771851]]
720 Cost:  2.69353557 
Prediction: 
 [[151.050674]
 [184.159256]
 [180.028763]
 [195.943817]
 [141.402084]
 [104.767181]]
730 Cost:  2.6873188 
Prediction: 
 [[151.055115]
 [184.157227]
 [180.030685]
 [195.94455]
 [141.399826]
 [104.762527]]
740 Cost:  2.68113732 
Prediction: 
 [[151.05954]
 [184.155212]
 [180.032593]
 [195.945251]
 [141.397583]
 [104.757889]]
750 Cost:  2.67498374 
Prediction: 
 [[151.063965]
 [184.153198]
 [180.0345]
 [195.945969]
 [141.39534]
 [104.753258]]
760 Cost:  2.66884255 
Prediction: 

1360 Cost:  2.35956311 
Prediction: 
 [[151.307785]
 [184.043076]
 [180.140457]
 [195.982697]
 [141.275513]
 [104.495369]]
1370 Cost:  2.35526586 
Prediction: 
 [[151.311386]
 [184.041458]
 [180.142014]
 [195.983185]
 [141.273804]
 [104.491531]]
1380 Cost:  2.35097384 
Prediction: 
 [[151.314957]
 [184.039841]
 [180.143585]
 [195.983673]
 [141.272079]
 [104.487679]]
1390 Cost:  2.34669328 
Prediction: 
 [[151.318558]
 [184.038254]
 [180.145172]
 [195.984177]
 [141.270401]
 [104.483849]]
1400 Cost:  2.3424511 
Prediction: 
 [[151.322113]
 [184.036652]
 [180.146729]
 [195.984665]
 [141.268707]
 [104.480026]]
1410 Cost:  2.33823 
Prediction: 
 [[151.325684]
 [184.035065]
 [180.148285]
 [195.985168]
 [141.267014]
 [104.476219]]
1420 Cost:  2.33403778 
Prediction: 
 [[151.329224]
 [184.033478]
 [180.149841]
 [195.985626]
 [141.26535]
 [104.472427]]
1430 Cost:  2.32987785 
Prediction: 
 [[151.332764]
 [184.031891]
 [180.151382]
 [195.98613]
 [141.263672]
 [104.468651]]
1440 Cost:  2.32573605

In [19]:
tf.print( 'Your score will be ',
         Hypothesis( [ [ 100., 70., 101. ] ] ) )
tf.print( 'Other scores will be ',
         Hypothesis( [ [ 60., 70., 110. ], [ 90., 100., 80. ] ] ) )

Your score will be  [[185.437744]]
Other scores will be  [[156.022659]
 [179.796844]]
