In [1]:
import tensorflow as tf
from tensorflow.keras import layers
import numpy as np

In [2]:
idx2char = [ 'h', 'i', 'e', 'l', 'o' ]

In [3]:
x_data = [ [ 0, 1, 0, 2, 3, 3 ] ] # hihell
x_one_hot = np.array( [ [
    [ 1, 0, 0, 0, 0 ],
    [ 0, 1, 0, 0, 0 ],
    [ 1, 0, 0, 0, 0 ],
    [ 0, 0, 1, 0, 0 ],
    [ 0, 0, 0, 1, 0 ],
    [ 0, 0, 0, 1, 0 ]
]], dtype = np.float32 )

y_data = [ [ 1, 0, 2, 3, 3, 4 ] ]
y_one_hot = tf.keras.utils.to_categorical( y_data, num_classes = 5 )

In [4]:
num_classes = 5
input_dim = 5
sequence_length = 6
learning_rate = 0.1

In [5]:
model = tf.keras.Sequential()

In [6]:
cell = layers.LSTMCell( units = num_classes,
                                input_shape = [ sequence_length, input_dim ] )
model.add( layers.RNN( cell = cell, return_sequences = True ) )

In [7]:
fc_layer = layers.Dense( units = num_classes, activation = 'softmax' )
model.add( layers.TimeDistributed( fc_layer ) )

In [8]:
model.compile( loss = 'categorical_crossentropy', optimizer = tf.keras.optimizers.Adam( learning_rate ),
              metrics = [ 'accuracy' ] )
model.fit( x_one_hot, y_one_hot, epochs = 50 )
model.summary()

Train on 1 samples
Epoch 1/50
1/1 [==============================] - 1s 769ms/sample - loss: 1.6286 - accuracy: 0.0000e+00
Epoch 2/50
1/1 [==============================] - 0s 6ms/sample - loss: 1.5294 - accuracy: 0.3333
Epoch 3/50
1/1 [==============================] - 0s 6ms/sample - loss: 1.4538 - accuracy: 0.3333
Epoch 4/50
1/1 [==============================] - 0s 5ms/sample - loss: 1.3900 - accuracy: 0.3333
Epoch 5/50
1/1 [==============================] - 0s 6ms/sample - loss: 1.3180 - accuracy: 0.3333
Epoch 6/50
1/1 [==============================] - 0s 6ms/sample - loss: 1.2168 - accuracy: 0.3333
Epoch 7/50
1/1 [==============================] - 0s 6ms/sample - loss: 1.1012 - accuracy: 0.5000
Epoch 8/50
1/1 [==============================] - 0s 6ms/sample - loss: 0.9907 - accuracy: 0.5000
Epoch 9/50
1/1 [==============================] - 0s 6ms/sample - loss: 0.8917 - accuracy: 0.6667
Epoch 10/50
1/1 [==============================] - 0s 6ms/sample - loss: 0.7978 - accuracy: 0

In [9]:
predictions = model.predict( x_one_hot )
for i, prediction in enumerate( predictions ):
    print( prediction )
    
    result_str = [ idx2char[ c ] for c in tf.argmax( prediction, axis = 1 ) ]
    print( 'Prediction str: ', ''.join( result_str ) )

[[9.4489346e-04 9.9314296e-01 4.5856116e-03 1.3234885e-03 3.1206173e-06]
 [9.9636734e-01 6.9260830e-05 2.9025198e-04 3.2723676e-03 8.6089278e-07]
 [7.5083175e-05 5.9667480e-04 9.8965865e-01 9.6692266e-03 3.3899653e-07]
 [6.7400304e-04 3.1196672e-04 1.2395372e-02 9.8655450e-01 6.4070329e-05]
 [7.6060183e-04 4.0811364e-04 1.5786013e-03 9.8962271e-01 7.6299608e-03]
 [2.2081369e-05 8.2555933e-05 9.7368720e-06 1.5169251e-02 9.8471642e-01]]
Prediction str:  ihello
