In [1]:
import tensorflow as tf

In [2]:
x_data = [
    [ 73., 80., 75. ],
    [ 93., 88., 93. ],
    [ 89., 91., 90. ],
    [ 96., 98., 100. ],
    [ 73., 66., 70. ]
]
y_data = [
    [ 152. ],
    [ 185. ],
    [ 180. ],
    [ 196. ],
    [ 142. ]
]

In [3]:
W = tf.Variable( tf.random.normal( [ 3, 1 ] ), name = 'W' )
b = tf.Variable( tf.random.normal( [ 1 ] ), name = 'b' )

In [5]:
def Hypothesis(X):
    return tf.matmul( X, W ) + b

def Cost(X, Y):
    return tf.reduce_mean(tf.square( Hypothesis( X ) - Y ) )

def Minimize(X, Y):
    loss = lambda : Cost(X, Y)
    tf.keras.optimizers.SGD( 1e-5 ).minimize( loss, [ W, b ] )

In [6]:
X = x_data
Y = y_data

for step in range( 2001 ):
    cost_val, hy_val = Cost( X, Y ), Hypothesis( X )
    Minimize( X, Y )
    if step % 10 == 0:
        tf.print( step, 'Cost: ', cost_val, '\nPrediction:\n', hy_val)

0 Cost:  16100.8848 
Prediction:
 [[40.9530449]
 [48.0395927]
 [48.1501389]
 [50.3687401]
 [37.9711723]]
10 Cost:  1.76315081 
Prediction:
 [[153.191422]
 [182.949844]
 [181.075287]
 [195.121628]
 [140.875122]]
20 Cost:  1.6093744 
Prediction:
 [[153.526733]
 [183.360947]
 [181.47612]
 [195.558884]
 [141.190094]]
30 Cost:  1.60302758 
Prediction:
 [[153.523468]
 [183.365082]
 [181.475983]
 [195.559464]
 [141.194626]]
40 Cost:  1.59671533 
Prediction:
 [[153.519211]
 [183.368]
 [181.474655]
 [195.558762]
 [141.198227]]
50 Cost:  1.59041369 
Prediction:
 [[153.514938]
 [183.370911]
 [181.473328]
 [195.558044]
 [141.201828]]
60 Cost:  1.58417189 
Prediction:
 [[153.510681]
 [183.373764]
 [181.47197]
 [195.557312]
 [141.205399]]
70 Cost:  1.57793343 
Prediction:
 [[153.506454]
 [183.376678]
 [181.470642]
 [195.55661]
 [141.208984]]
80 Cost:  1.57175946 
Prediction:
 [[153.502228]
 [183.379547]
 [181.46933]
 [195.555908]
 [141.21254]]
90 Cost:  1.5656085 
Prediction:
 [[153.498016]
 [183.38

780 Cost:  1.2108 
Prediction:
 [[153.232269]
 [183.562836]
 [181.384338]
 [195.511856]
 [141.4384]]
790 Cost:  1.20654321 
Prediction:
 [[153.22876]
 [183.565216]
 [181.383224]
 [195.511307]
 [141.441315]]
800 Cost:  1.20230603 
Prediction:
 [[153.22525]
 [183.567596]
 [181.382126]
 [195.510757]
 [141.444229]]
810 Cost:  1.19810319 
Prediction:
 [[153.221771]
 [183.569977]
 [181.381042]
 [195.510208]
 [141.447144]]
820 Cost:  1.19391489 
Prediction:
 [[153.218307]
 [183.572342]
 [181.379929]
 [195.509689]
 [141.450012]]
830 Cost:  1.18976045 
Prediction:
 [[153.214844]
 [183.574692]
 [181.37883]
 [195.509125]
 [141.452896]]
840 Cost:  1.18561614 
Prediction:
 [[153.211349]
 [183.577026]
 [181.377747]
 [195.508575]
 [141.45578]]
850 Cost:  1.18151057 
Prediction:
 [[153.207916]
 [183.579361]
 [181.376648]
 [195.508026]
 [141.458633]]
860 Cost:  1.17740512 
Prediction:
 [[153.204468]
 [183.581711]
 [181.375565]
 [195.507492]
 [141.461487]]
870 Cost:  1.17333198 
Prediction:
 [[153.20103

1550 Cost:  0.94085753 
Prediction:
 [[152.987442]
 [183.728775]
 [181.30687]
 [195.474686]
 [141.64032]]
1560 Cost:  0.938020885 
Prediction:
 [[152.984589]
 [183.730713]
 [181.305954]
 [195.474274]
 [141.642654]]
1570 Cost:  0.93518889 
Prediction:
 [[152.98172]
 [183.732651]
 [181.305038]
 [195.473846]
 [141.644989]]
1580 Cost:  0.932385445 
Prediction:
 [[152.978882]
 [183.734589]
 [181.304153]
 [195.47345]
 [141.647324]]
1590 Cost:  0.929586053 
Prediction:
 [[152.976028]
 [183.736511]
 [181.303238]
 [195.473022]
 [141.649628]]
1600 Cost:  0.926806927 
Prediction:
 [[152.97319]
 [183.738419]
 [181.302338]
 [195.472626]
 [141.651947]]
1610 Cost:  0.924040318 
Prediction:
 [[152.970383]
 [183.740341]
 [181.301437]
 [195.472214]
 [141.654282]]
1620 Cost:  0.921280086 
Prediction:
 [[152.96756]
 [183.742264]
 [181.300537]
 [195.471817]
 [141.656555]]
1630 Cost:  0.918552697 
Prediction:
 [[152.964737]
 [183.744156]
 [181.299652]
 [195.47139]
 [141.658859]]
1640 Cost:  0.915833771 
Pre