In [1]:
import tensorflow as tf
import numpy as np

In [2]:
x_data = np.array( [
    [ 0, 0 ],
    [ 0, 1 ],
    [ 1, 0 ],
    [ 1, 1 ],
], dtype = np.float32 )

y_data = np.array( [
    [ 0 ],
    [ 1 ],
    [ 1 ],
    [ 0 ]
], dtype = np.float32 )

In [3]:
writer = tf.summary.create_file_writer('./log')

In [4]:
W1 = tf.Variable( tf.random.normal( [ 2, 2 ] ), name = 'weight1' )
b1 = tf.Variable( tf.random.normal( [ 2 ] ), name = 'bias' )
tf.summary.histogram( 'W1', W1)
tf.summary.histogram( 'b1', b1)

<tf.Tensor: shape=(), dtype=bool, numpy=False>

In [5]:
W2 = tf.Variable( tf.random.normal( [ 2, 1 ] ), name = 'weight2' )
b2 = tf.Variable( tf.random.normal( [ 1 ] ), name = 'bias2' )
tf.summary.histogram( 'W2', W2)
tf.summary.histogram( 'b2', b2)

<tf.Tensor: shape=(), dtype=bool, numpy=False>

In [9]:
@tf.function
def Layer1( X ):
    return ( tf.math.sigmoid( tf.matmul( X, W1 ) + b1 ) )

@tf.function
def Hypothesis( X ):
    return ( tf.math.sigmoid( tf.matmul( Layer1( X ), W2 ) + b2 ) )

@tf.function
def Cost( X, Y ):
    hypothesis = Hypothesis( X )
    former = Y * tf.math.log( hypothesis )
    latter = tf.subtract( 1., Y ) * tf.math.log( 1. - hypothesis )
    return ( -tf.reduce_mean( former + latter ) )

def Minimize( X, Y ):
    loss = lambda: Cost( X, Y )
    
    tf.keras.optimizers.SGD( 0.1 ).minimize( loss, [ W1, W2, b1, b2 ] )

In [6]:
def Predict( X ):
    return ( tf.cast( Hypothesis( X ) > 0.5, dtype = tf.float32 ) )

def Accuracy( X, Y ):
    return ( tf.reduce_mean( tf.cast( tf.equal( Predict( X ), Y ),
                                     dtype = tf.float32 ) ) )

In [12]:
for step in range( 10001 ):
    Minimize( x_data, y_data )
    if ( step % 100 == 0 ):
        tf.print( step, Cost( x_data, y_data ) )

0 0.772670865
100 0.695645213
200 0.692468762
300 0.689137
400 0.685365915
500 0.680881858
600 0.675353408
700 0.668323159
800 0.659074
900 0.646354795
1000 0.627940834
1100 0.60077107
1200 0.563843131
1300 0.520185828
1400 0.472339123
1500 0.42211625
1600 0.372293711
1700 0.325674474
1800 0.284069657
1900 0.248134077
2000 0.217694014
2100 0.192150116
2200 0.170767367
2300 0.152832285
2400 0.137718901
2500 0.124905095
2600 0.113966979
2700 0.104564197
2800 0.096424818
2900 0.0893317312
3000 0.0831106603
3100 0.0776214749
3200 0.0727505088
3300 0.0684051961
3400 0.0645096749
3500 0.0610012263
3600 0.0578277335
3700 0.0549458303
3800 0.0523188487
3900 0.0499158353
4000 0.0477105826
4100 0.0456805266
4200 0.0438064635
4300 0.0420717
4400 0.0404617861
4500 0.0389642268
4600 0.0375679731
4700 0.0362635329
4800 0.0350423306
4900 0.0338968746
5000 0.0328205973
5100 0.031807594
5200 0.0308524743
5300 0.029950738
5400 0.0290979724
5500 0.0282905512
5600 0.0275249016
5700 0.026798062
5800 0.0261

In [13]:
X, Y = x_data, y_data
h, c, a = Hypothesis( X ), Predict( X ), Accuracy( X, Y )
tf.print( h, c, a, sep = '\n' )

[[0.0119653707]
 [0.984087169]
 [0.988962829]
 [0.010168314]]
[[0]
 [1]
 [1]
 [0]]
1
