# Tensor Manipulation

In [1]:
import tensorflow as tf
import numpy as np
import pprint

pp = pprint.PrettyPrinter( indent = 4 )

# Simple Array

In [2]:
t = np.array( [ 0., 1., 2., 3., 4., 5., 6. ] )

pp.pprint( t )
print( t.ndim )
print( t.shape )
print( t[0], t[1], t[-1] )
print( t[ 2:5 ], t[ 4:-1 ])
print( t[:2], t[3:] )

array([0., 1., 2., 3., 4., 5., 6.])
1
(7,)
0.0 1.0 6.0
[2. 3. 4.] [4. 5.]
[0. 1.] [3. 4. 5. 6.]


# 2D Array

In [3]:
t = np.array( [
    [ 1., 2., 3. ],
    [ 4., 5., 6. ],
    [ 7., 8., 9. ],
    [ 10., 11., 12. ]
])

pp.pprint( t )
print( t.ndim )
print( t.shape )

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]])
2
(4, 3)


# Shape, Rank, Axis

In [4]:
t = tf.constant( [ 1, 2, 3, 4 ] )
tf.print( tf.shape( t ) )

[4]


In [5]:
t = tf.constant( [ [ 1, 2 ], [ 3, 4 ] ] )
tf.print( tf.shape( t ) )

[2 2]


In [6]:
t = tf.constant(
    [
        [
            [
                [1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]
            ],
            [
                [13, 14, 15, 16],
                [17, 18, 19, 20],
                [21, 22, 23, 24]
            ]
        ]
    ]
)

tf.print( tf.shape( t ) )

[1 2 3 4]


# Matnul VS multiply

In [7]:
matrix1 = tf.constant( [ [ 1., 2. ], [ 3., 4. ] ] )
matrix2 = tf.constant( [ [ 1. ], [ 2. ] ] )
print( matrix1.shape )
print( matrix2.shape )
tf.print( tf.matmul( matrix1, matrix2 ) )

(2, 2)
(2, 1)
[[5]
 [11]]


In [8]:
tf.print( matrix1 * matrix2 )

[[1 2]
 [6 8]]


# Watch out broadcasting

In [9]:
matrix1 = tf.constant( [ [ 3., 3. ] ] )
matrix2 = tf.constant( [ [ 2., 2. ] ] )
tf.print( matrix1 + matrix2 )

[[5 5]]


In [10]:
matrix1 = tf.constant( [ [ 1., 2. ] ] )
matrix2 = tf.constant( 3. )
tf.print( matrix1 + matrix2 )

[[4 5]]


In [11]:
matrix1 = tf.constant( [ [ 1., 2. ] ] )
matrix2 = tf.constant( [ 3., 4. ] )
tf.print( matrix1 + matrix2 )

[[4 6]]


In [12]:
matrix1 = tf.constant( [ [ 1., 2. ] ] )
matrix2 = tf.constant( [ [ 3. ], [ 4. ] ] )
tf.print( matrix1 + matrix2 )

[[4 5]
 [5 6]]


# Random values for variable initializionts

In [13]:
tf.print( tf.random.normal( [ 3 ] ) )

[-0.401158512 1.42210531 1.49078989]


In [14]:
tf.print( tf.random.uniform( [ 2 ] ) )

[0.454143167 0.367045164]


In [15]:
tf.print( tf.random.uniform( [ 2, 3 ] ) )

[[0.334801435 0.0110433102 0.21033895]
 [0.833604693 0.999962091 0.544125915]]


# Reduce Mean/Sum

In [16]:
tf.print( tf.reduce_mean( [ 1, 2 ], axis = 0 ) )
tf.print( tf.reduce_mean( [ 1., 2. ], axis = 0 ) )

1
1.5


In [17]:
x = [
    [ 1., 2. ],
    [ 3., 4. ]
]

tf.print( tf.reduce_mean( x ) )
tf.print( tf.reduce_mean( x, axis = 0 ) )
tf.print( tf.reduce_mean( x, axis = 1 ) )
tf.print( tf.reduce_mean( x, axis = -1 ) )

2.5
[2 3]
[1.5 3.5]
[1.5 3.5]


In [18]:
tf.print( tf.reduce_sum( x ) )
tf.print( tf.reduce_sum( x, axis = 0 ) )
tf.print( tf.reduce_sum( x, axis = 1 ) )
tf.print( tf.reduce_sum( x, axis = -1 ) )

10
[4 6]
[3 7]
[3 7]


# Argmax with axis

In [19]:
x = [
    [ 0, 1, 2 ],
    [ 2, 1, 0 ]
]

tf.print( tf.argmax( x, axis = 0 ) )
tf.print( tf.argmax( x, axis = 1 ) )
tf.print( tf.argmax( x, axis = -1 ) )

[1 0 0]
[2 0]
[2 0]


# Reshape, squeeze, expand_dims

In [20]:
t = np.array([
        [
            [ 0, 1, 2 ],
            [ 3, 4, 5 ]
        ],
        [
            [ 6, 7, 8 ],
            [ 9, 10, 11 ]
        ]
    ])

t.shape

(2, 2, 3)

In [21]:
tf.print( tf.reshape( t, shape = [ -1, 3 ] ) )

[[0 1 2]
 [3 4 5]
 [6 7 8]
 [9 10 11]]


In [22]:
tf.print( tf.reshape( t, shape = [ -1, 1, 3 ] ) )

[[[0 1 2]]

 [[3 4 5]]

 [[6 7 8]]

 [[9 10 11]]]


In [23]:
tf.print( tf.squeeze( [ [ 0 ], [ 1 ], [ 2 ] ] ) )
tf.print( tf.expand_dims( [ 0, 1, 2 ], 1 ) )

[0 1 2]
[[0]
 [1]
 [2]]


# One hot

In [24]:
tf.print( tf.one_hot( [ [ 0 ], [ 1 ], [ 2 ], [ 0 ] ], depth = 3 ) )

[[[1 0 0]]

 [[0 1 0]]

 [[0 0 1]]

 [[1 0 0]]]


In [25]:
t = tf.one_hot( [ [ 0 ], [ 1 ], [ 2 ], [ 0 ] ], depth = 3 )
tf.print( tf.reshape( t, shape = [ -1, 3 ] ) )

[[1 0 0]
 [0 1 0]
 [0 0 1]
 [1 0 0]]


# casting

In [26]:
tf.print( tf.cast ( [ 1.8, 2.2, 3.3, 4.9 ], tf.int32 ) )

[1 2 3 4]


In [27]:
tf.print( tf.cast( [ True, False, 1 == 1, 0 == 1 ], tf.int32 ) )

[1 0 1 0]


# Stack

In [28]:
x = [ 1, 4 ]
y = [ 2, 5 ]
z = [ 3, 6 ]
tf.print( tf.stack( [ x, y, z ] ) )

[[1 4]
 [2 5]
 [3 6]]


In [29]:
tf.print( tf.stack( [ x, y, z ], axis = 0 ) )
tf.print( tf.stack( [ x, y, z ], axis = 1 ) )

[[1 4]
 [2 5]
 [3 6]]
[[1 2 3]
 [4 5 6]]


# Ones like and Zeros like

In [30]:
x = [
    [ 0, 1, 2 ],
    [ 2, 1, 0 ]
]

tf.print( tf.ones_like( x ) )
tf.print( tf.zeros_like( x ) )

[[1 1 1]
 [1 1 1]]
[[0 0 0]
 [0 0 0]]


# Zip

In [31]:
for x, y in zip( [ 1, 2, 3 ], [ 4, 5, 6 ] ):
    print( x, y )

1 4
2 5
3 6


In [32]:
for x, y, z in zip( [ 1, 2, 3 ], [ 4, 5, 6 ], [ 7, 8, 9 ] ):
    print( x, y, z )

1 4 7
2 5 8
3 6 9


# Transpose

In [33]:
t = np.array( [
    [
        [ 0, 1, 2 ],
        [ 3, 4, 5 ],
    ],
    [
        [ 6, 7, 8 ],
        [ 9, 10, 11]
    ]
]
)
pp.pprint( t.shape )
pp.pprint( t )

(2, 2, 3)
array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])


In [34]:
t1 = tf.transpose( t, [ 1, 0 ,2 ] )
pp.pprint( t1.shape )
tf.print( t1 )

TensorShape([2, 2, 3])
[[[0 1 2]
  [6 7 8]]

 [[3 4 5]
  [9 10 11]]]


In [35]:
t = tf.transpose( t1, [ 1, 0 ,2 ] )
pp.pprint( t.shape )
tf.print( t )

TensorShape([2, 2, 3])
[[[0 1 2]
  [3 4 5]]

 [[6 7 8]
  [9 10 11]]]


In [36]:
t2 = tf.transpose( t, [ 1, 2, 0 ] )
tf.print( t2.shape )
tf.print( t2 )

TensorShape([2, 3, 2])
[[[0 6]
  [1 7]
  [2 8]]

 [[3 9]
  [4 10]
  [5 11]]]


In [37]:
t = tf.transpose( t2, [ 2, 0, 1 ] )
tf.print( t.shape )
tf.print( t )

TensorShape([2, 2, 3])
[[[0 1 2]
  [3 4 5]]

 [[6 7 8]
  [9 10 11]]]
