In [1]:
import tensorflow as tf

In [2]:
x1_data = [ 73., 93., 89., 96., 73. ]
x2_data = [ 80., 88., 91., 98., 66. ]
x3_data = [ 75., 93., 90., 100., 70. ]

y_data = [ 152., 185., 180., 96., 142. ]

In [3]:
w1 = tf.Variable( tf.random.normal( [ 1 ] ), name = 'weight1' )
w2 = tf.Variable( tf.random.normal( [ 1 ] ), name = 'weight2' )
w3 = tf.Variable( tf.random.normal( [ 1 ] ), name = 'weight3' )
b = tf.Variable( tf.random.normal( [ 1 ] ), name = 'bias' )

In [4]:
def Hypothesis( X1, X2, X3 ):
    return  X1 * w1 + X2 * w2 + X3 * w3 + b

def Cost( X1, X2, X3, Y ):
    return tf.reduce_mean( tf.square( Hypothesis( X1, X2, X3 ) - Y ) )

def Minimize( X1, X2, X3, Y ):
    loss = lambda : Cost(X1, X2, X3, Y)
    tf.keras.optimizers.SGD( 1e-5 ).minimize( loss, [ w1, w2, w3, b ] )

In [5]:
X1 = x1_data
X2 = x2_data
X3 = x3_data
Y = y_data

for step in range( 2001 ):
    cost_val, hy_val = Cost( X1, X2, X3, Y ), Hypothesis( X1, X2, X3 )
    Minimize( X1, X2, X3, Y )
    if step % 10 == 0:
        tf.print( step, 'Cost: ', cost_val, '\nPrediction:\n', hy_val)

0 Cost:  42460.7578 
Prediction:
 [-42.1782417 -59.3199806 -54.2191277 -54.9621391 -51.0237617]
10 Cost:  1757.82788 
Prediction:
 [136.251541 155.214844 157.127777 175.176544 112.641754]
20 Cost:  1756.10913 
Prediction:
 [136.752502 155.892273 157.757446 175.849426 113.187889]
30 Cost:  1754.76758 
Prediction:
 [136.715256 155.922562 157.749603 175.828064 113.240356]
40 Cost:  1753.43042 
Prediction:
 [136.676483 155.950821 157.739838 175.804626 113.291222]
50 Cost:  1752.09766 
Prediction:
 [136.637817 155.978973 157.730133 175.781219 113.34198]
60 Cost:  1750.76929 
Prediction:
 [136.599289 156.007034 157.720444 175.757828 113.392593]
70 Cost:  1749.44592 
Prediction:
 [136.560852 156.035 157.7108 175.734467 113.443085]
80 Cost:  1748.12573 
Prediction:
 [136.522583 156.062927 157.701202 175.711151 113.493507]
90 Cost:  1746.8103 
Prediction:
 [136.48439 156.090744 157.691635 175.687851 113.543785]
100 Cost:  1745.49927 
Prediction:
 [136.446381 156.1185 157.682129 175.664612 113.5

900 Cost:  1652.81409 
Prediction:
 [133.76915 158.084747 157.030197 173.896576 117.265678]
910 Cost:  1651.78809 
Prediction:
 [133.739914 158.1064 157.023315 173.875549 117.307602]
920 Cost:  1650.76563 
Prediction:
 [133.710785 158.127975 157.016479 173.854568 117.349426]
930 Cost:  1649.74487 
Prediction:
 [133.681778 158.149506 157.009689 173.833603 117.391167]
940 Cost:  1648.72791 
Prediction:
 [133.652847 158.170959 157.002899 173.812668 117.432816]
950 Cost:  1647.71423 
Prediction:
 [133.624008 158.192337 156.99614 173.791763 117.474373]
960 Cost:  1646.70215 
Prediction:
 [133.595276 158.213654 156.98941 173.770859 117.515831]
970 Cost:  1645.69312 
Prediction:
 [133.56665 158.234909 156.982727 173.75 117.557205]
980 Cost:  1644.68774 
Prediction:
 [133.538101 158.256088 156.976059 173.729172 117.598495]
990 Cost:  1643.68396 
Prediction:
 [133.509644 158.277206 156.969421 173.708344 117.639694]
1000 Cost:  1642.68298 
Prediction:
 [133.481293 158.298264 156.962814 173.68754

1790 Cost:  1571.24426 
Prediction:
 [131.520401 159.769028 156.524719 172.118 120.665359]
1800 Cost:  1570.42456 
Prediction:
 [131.498856 159.785385 156.520157 172.099 120.700043]
1810 Cost:  1569.6062 
Prediction:
 [131.477402 159.801682 156.515625 172.08 120.734634]
1820 Cost:  1568.79016 
Prediction:
 [131.456009 159.817932 156.511108 172.06105 120.769188]
1830 Cost:  1567.97607 
Prediction:
 [131.434692 159.834137 156.506622 172.042114 120.803642]
1840 Cost:  1567.1637 
Prediction:
 [131.413452 159.850281 156.502136 172.023193 120.838036]
1850 Cost:  1566.35327 
Prediction:
 [131.392273 159.866364 156.497681 172.004288 120.872353]
1860 Cost:  1565.54419 
Prediction:
 [131.371185 159.882416 156.493271 171.985413 120.906609]
1870 Cost:  1564.73694 
Prediction:
 [131.350174 159.898392 156.488861 171.966537 120.940788]
1880 Cost:  1563.93201 
Prediction:
 [131.329224 159.914322 156.484467 171.947693 120.974892]
1890 Cost:  1563.12842 
Prediction:
 [131.30838 159.930237 156.480133 171