In [1]:
import tensorflow as tf
from tensorflow.keras import layers
import numpy as np

In [2]:
h = [ 1, 0, 0, 0 ]
e = [ 0, 1, 0, 0 ]
l = [ 0, 0, 1, 0 ]
o = [ 0, 0, 0, 1 ]

In [5]:
hidden_size = 2
cell = tf.keras.layers.SimpleRNNCell( units = hidden_size )
print( cell.output_size, cell.state_size )

x_data = np.array( [ [ h ] ], dtype = np.float32 )
print( x_data )
rnn = tf.keras.layers.RNN( cell )
outputs = rnn( x_data )

print( outputs )

2 2
[[[1. 0. 0. 0.]]]
tf.Tensor([[-0.18906415 -0.5875595 ]], shape=(1, 2), dtype=float32)


In [6]:
hidden_size = 2
cell = tf.keras.layers.SimpleRNNCell( units = hidden_size,
                                    input_shape = [ 5, 4 ] )

x_data = np.array( [ [ h, e, l, l, o ] ], dtype = np.float32 )
print( x_data.shape )

rnn = tf.keras.layers.RNN( cell )
output = rnn( x_data )
print( output )

(1, 5, 4)
tf.Tensor([[ 0.80902034 -0.81391525]], shape=(1, 2), dtype=float32)


In [10]:
hidden_size = 2
sequence_length = 5
model2 = tf.keras.Sequential()

x_data = np.array( [ [ h, e, l, l, o ] ], dtype = np.float32 )
print( x_data.shape )

cell = layers.SimpleRNNCell( units = hidden_size,
                            input_shape = [ sequence_length, 4 ] )
model2.add( layers.RNN( cell = cell ) )

# print( model2.evaluate() )

(1, 5, 4)


ValueError: This model has not yet been built. Build the model first by calling `build()` or calling `fit()` with some data, or specify an `input_shape` argument in the first layer(s) for automatic build.