In [1]:
import tensorflow as tf

In [2]:
x_data = [
    [ 1, 2, 1, 1 ],
    [ 2, 1, 3, 2 ],
    [ 3, 1, 3, 4 ],
    [ 4, 1, 5, 5 ],
    [ 1, 7, 5, 5 ],
    [ 1, 2, 5, 6 ],
    [ 1, 6, 6, 6 ],
    [ 1, 7, 7, 7 ]
]

y_data = [
    [ 0, 0, 1 ],
    [ 0, 0, 1 ],
    [ 0, 0, 1 ],
    [ 0, 1, 0 ],
    [ 0, 1, 0 ],
    [ 0, 1, 0 ],
    [ 1, 0, 0 ],
    [ 1, 0, 0 ]
]

In [3]:
nb_classes = 3

In [4]:
W = tf.Variable( tf.random.normal( [ 4, nb_classes ] ), name = 'weight' )
b = tf.Variable( tf.random.normal( [ nb_classes ] ), name = 'bias' )

In [5]:
@tf.function
def Hypothesis( X ):
    X = tf.cast( X, dtype = tf.float32)
    return ( tf.nn.softmax( tf.matmul( X, W ) + b ) )

@tf.function
def Cost( X, Y ):
    return (
        tf.reduce_mean( -tf.reduce_sum( Y * tf.math.log( Hypothesis( X ) ), axis = 1 ) )
     )
        
def Minimize( X, Y ):
    loss = lambda : Cost( X, Y )
    tf.keras.optimizers.SGD( 0.01 ).minimize( loss, [ W, b ] )

In [11]:
X = x_data
Y = y_data
Hypothesis( X )
Cost( X, Y )
for step in range( 2001 ):
    Minimize( X, Y )
    if ( step % 200 == 0 ):
        tf.print( step, Cost( X, Y ) )

0 0.238815188
200 0.236372709
400 0.233977109
600 0.231627196
800 0.229321823
1000 0.227059245
1200 0.224838674
1400 0.2226592
1600 0.220519304
1800 0.218418121
2000 0.216354609


In [7]:
a = Hypothesis( [ [ 1, 11, 7, 9 ] ] )
tf.print( a, tf.math.argmax( a, 1 ) )

[[0.959898651 0.0399725921 0.000128695319]] [0]


In [8]:
all = Hypothesis( [ [ 1, 11, 7, 9 ], [ 1, 3, 4, 3 ], [ 1, 1, 0, 1 ] ] )
tf.print( all, tf.math.argmax( all, 1) )

[[0.959898651 0.0399725735 0.000128695319]
 [0.130315468 0.641198218 0.228486285]
 [0.00803382322 0.0731669515 0.918799162]] [0 1 2]
