In [1]:
import tensorflow as tf
from tensorflow.keras import layers
import numpy as np

In [2]:
idx2char = [ 'h', 'i', 'e', 'l', 'o' ]

In [3]:
x_data = [ [ 0, 1, 0, 2, 3, 3 ] ] # hihell
x_one_hot = np.array( [ [
    [ 1, 0, 0, 0, 0 ],
    [ 0, 1, 0, 0, 0 ],
    [ 1, 0, 0, 0, 0 ],
    [ 0, 0, 1, 0, 0 ],
    [ 0, 0, 0, 1, 0 ],
    [ 0, 0, 0, 1, 0 ]
]], dtype = np.float32 )

y_data = [ [ 1, 0, 2, 3, 3, 4 ] ]
y_one_hot = tf.keras.utils.to_categorical( y_data, num_classes = 5 )

In [4]:
num_classes = 5
input_dim = 5
sequence_length = 6
learning_rate = 0.1

In [5]:
model = tf.keras.Sequential()

In [6]:
cell = layers.LSTMCell( units = num_classes,
                                input_shape = [ sequence_length, input_dim ] )
model.add( layers.RNN( cell = cell, return_sequences = True ) )

In [7]:
fc_layer = layers.Dense( units = num_classes, activation = 'softmax' )
model.add( layers.TimeDistributed( fc_layer ) )

In [8]:
model.compile( loss = 'categorical_crossentropy', optimizer = tf.keras.optimizers.Adam( learning_rate ),
              metrics = [ 'accuracy' ] )
model.fit( x_one_hot, y_one_hot, epochs = 50 )
model.summary()

Train on 1 samples
Epoch 1/50
1/1 [==============================] - 1s 725ms/sample - loss: 1.6650 - accuracy: 0.0000e+00
Epoch 2/50
1/1 [==============================] - 0s 6ms/sample - loss: 1.5452 - accuracy: 0.3333
Epoch 3/50
1/1 [==============================] - 0s 6ms/sample - loss: 1.4723 - accuracy: 0.3333
Epoch 4/50
1/1 [==============================] - 0s 6ms/sample - loss: 1.4131 - accuracy: 0.3333
Epoch 5/50
1/1 [==============================] - 0s 7ms/sample - loss: 1.3462 - accuracy: 0.3333
Epoch 6/50
1/1 [==============================] - 0s 7ms/sample - loss: 1.2629 - accuracy: 0.3333
Epoch 7/50
1/1 [==============================] - 0s 6ms/sample - loss: 1.1655 - accuracy: 0.3333
Epoch 8/50
1/1 [==============================] - 0s 6ms/sample - loss: 1.0706 - accuracy: 0.6667
Epoch 9/50
1/1 [==============================] - 0s 6ms/sample - loss: 0.9782 - accuracy: 0.6667
Epoch 10/50
1/1 [==============================] - 0s 6ms/sample - loss: 0.8787 - accuracy: 0

In [9]:
predictions = model.predict( x_one_hot )
for i, prediction in enumerate( predictions ):
    print( prediction )
    
    result_str = [ idx2char[ c ] for c in tf.argmax( prediction, axis = 1 ) ]
    print( 'Prediction str: ', ''.join( result_str ) )

[[7.2356675e-06 9.9819618e-01 7.9735141e-04 9.9924661e-04 8.1174889e-09]
 [9.9510539e-01 7.6592994e-05 4.7574709e-03 3.5848939e-07 6.0154547e-05]
 [2.5782877e-04 7.1245310e-04 9.9621272e-01 2.8155919e-03 1.4685540e-06]
 [2.3770196e-08 9.1840891e-04 8.3051086e-04 9.9820781e-01 4.3287302e-05]
 [6.8653196e-07 2.9997871e-04 5.9080037e-04 9.9065137e-01 8.4571494e-03]
 [2.2920245e-05 1.3447377e-07 7.5588599e-05 5.7778656e-03 9.9412352e-01]]
Prediction str:  ihello
